# Generated by Django 5.0.7 on 2024-07-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.PositiveIntegerField()),
                ('date_of_field', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('others', 'others')], default='others', max_length=25)),
                ('skills', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('1', 'Koshi'), ('2', 'Madhesh'), ('3', 'Bagmati'), ('4', 'Gandaki'), ('5', 'Lumbini'), ('6', 'Karnali'), ('7', 'Sudhurpaschim')], default='3', max_length=25)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employee_profile_picture/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='employee_resume/')),
                ('video', models.FileField(blank=True, null=True, upload_to='employee_video/')),
            ],
        ),
    ]
