# Generated by Django 5.0.7 on 2024-07-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_attendence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendence',
            new_name='Attendance',
        ),
    ]
